### ISSUE TITLE
**Suggestion** If game could automatically to you back to Hallway

### ISSUE THREAD

**Issue by Villalpando2021** [luceroweb/haunted-house-game#103]
## Environment
Device: HP ProBook 440 G7 -
Version: 10.0.19042 Build 19041
Browser: Google Chrome Version 93.0.4577.63 (Official Build) (64-bit)
User type: User

## Description
When passing a challenge it takes me back to the room I chose(Library) Instead of taking me back to the hallway 

## Expected Behavior
When passing a challenge and being able to continue the game. The game should take you back to hallway instead of taking you back to previous room where you still got to click on the Back To Hallway button.

## Actual Behavior
Takes you to the room you chose instead of the hallway .

## Steps to Reproduce Issue
1.Go to https://luceroweb.github.io/haunted-house-game
2.Skip to play
3.Pick a room
4.Searh room and if you don't die it will take you back to same room

**Comment by luceroweb** [comment]
@ProjectErostribe is our Haunted House story editor, and @SmiJa is our design editor. Do you guys think that game play will improve by automatically moving the user back to the hallway, or should we continue requiring the user to choose to leave the room and return to the hallway?

CC @Villalpando2021 @lreyes-qae

**Comment by ProjectErostribe** [comment]
Thank you for your suggestion, but this is a feature not a bug.
