### ISSUE TITLE
Werewolf grammar errors

### ISSUE THREAD

**Issue by ghost** [luceroweb/haunted-house-game#106]
Device name: JHWork Laptop

Desktop OS: Linux Ubuntu 20.04.01 64bit
Browsers: Chrome/Firefox
Device: Ipad 6th gen.
IOS: 14.8

Description:
The Werewolf page has grammar errors on the second line in the paragraph . The line shows "just out your reach"

Expected Behavior:
User should be able to read complete and correct sentences. 

Actual Behavior:
The line should show "just out of your reach"

Steps to reproduce issue:
1.Goto website 
2.Click into Game 
3.Click Living Room
4.Clicked on Search Room(game randomly selected Werewolf

Screen Shots

<img width="650" alt="werewolfgrammar" src="https://user-images.githubusercontent.com/93013827/139156676-4fe444a4-9ca4-48d4-b5dc-c1767b05336d.png">
:

**Comment by luceroweb** [comment]
@ProjectErostribe is our Haunted House story editor. Myles, could you add the word "of" to the werewolf story where it says "just out your reach" as recommended?

cc @jennah559 @lreyes-qae

**Comment by ProjectErostribe** [comment]
@luceroweb I agree with this suggestion.  I have made the change.

**Comment by luceroweb** [comment]
@jennah559 could you please confirm if the issue has been resolved?
cc @ProjectErostribe @lreyes-qae

**Comment by ghost** [comment]
Hi,

Confirming fixed. Thank You.


*Jennifer Hughes* (She/Her)
QA Apprentice | Bitwise Industries
 ***@***.*** | bitwiseindustries.com/
<https://bitwiseindustries.com>
700 Van Ness Avenue, Fresno, CA 93721
Stay up-to-date on everything Bitwise
<https://bitwiseindustries.com/everything-bitwise/>
