### ISSUE TITLE
Chainsaw Murderer page- spelling & punctuation errors

### ISSUE THREAD

**Issue by ghost** [luceroweb/haunted-house-game#110]
Device name: JHWork Laptop
Desktop OS: Linux Ubuntu 20.04.01 64bit
Browsers: Chrome/Firefox/
Device: Ipad 6th gen.
IOS: 14.8

Description:
Chainsaw Murderer page spelling & punctuation errors.

Expected Behavior:
User should expect to be able to read full correct sentences.

Actual Behavior:
Spelling and punctuation issues on chainsaw murder page. First sentence and within the second sentence the word "REVING and REVVING" are listed. The correct spelling is "REVVING"

Steps to reproduce issue:
1.Goto website 
2.Click into Game 
3.Click Library Room (Or any Room)
4.Clicked on Search Room(game randomly selected chainsaw murderer)

Screen Shots:
![MurdererSpelling](https://user-images.githubusercontent.com/93013827/139158425-55a8b998-f494-4fa8-8d61-9c5b461a8edf.png)

**Comment by ProjectErostribe** [comment]
@jennah559 This has been changed.

**Comment by luceroweb** [comment]
@jennah559 could you please confirm whether the text is updated as you requested so we can close this issue?
cc @ProjectErostribe @lreyes-qae

**Comment by ghost** [comment]
Hi ,

This looks Great. Thank You

*Jennifer Hughes* (She/Her)
QA Apprentice | Bitwise Industries
 ***@***.*** | bitwiseindustries.com/
<https://bitwiseindustries.com>
700 Van Ness Avenue, Fresno, CA 93721
Stay up-to-date on everything Bitwise
<https://bitwiseindustries.com/everything-bitwise/>
