### ISSUE TITLE
Golden Key story line inconsistency

### ISSUE THREAD

**Issue by migriva** [luceroweb/haunted-house-game#112]
## ***Environment***
Device: Dell Precision 3560
Processor: 11th Gen Intel® Core™ i5-1135G7 @ 2.40GHz × 8 
Browser: Google Chrome Version 95.0.4638.54 (Official Build) (64-bit)
User type: User

## ***Description***

There is an inconsistency in the storyline at this point.

## ***Expected Behavior***

The user expects that the text and storyline be consistent throughout the game.  At this point in the game the user, themself has the Golden Key.

## ***Actual Behavior***

The text states that Juan takes the key out of his pocket and follows through with an action.

## ***Steps to Reproduce Issue***
1. Go to website
2. Navigate through game until you reach the Alien
3. Accept the key from the Alien.
4. Navigate back to the Hallway.
5. Choose Present Key.

## ***Screenshot***

![GoldKey](https://user-images.githubusercontent.com/93154253/139158699-46d576b5-cefa-4fac-8a79-46f64355789f.jpg)

## ***Notes***
Following is a suggestion.  This could possibly be an improvement to the storyline.

"You take the Golden Key from your pocket and attempt to insert it into the door lock.  Just as the tip of the key touches the lock it smashes into a mess.  The gold wrapping peels away to reveal semi-melted chocolate!!!

You were tricked by the Alien!!! Keep trying to win the Silver Key... It's the only way!"

**Comment by luceroweb** [comment]
@ProjectErostribe is our Haunted House story editor. Myles should we modify the gold key story to indicate the player rather than Juan?

cc @migriva @lreyes-qae

**Comment by ProjectErostribe** [comment]
@migriva @lreyes-qae Thank you for this suggestion, the suggested changes have been made.

**Comment by migriva** [comment]
I'm glad I could provide a welcome and useful suggestion keep up the good
work!!!

**Comment by migriva** [comment]
Hey cool love the game!!!
