### ISSUE TITLE
Refresh browser icon is not refreshing within current page.

### ISSUE THREAD

**Issue by ghost** [luceroweb/haunted-house-game#114]
Device name: JHWork Laptop
Desktop OS: Linux Ubuntu 20.04.01 64bit
Browsers: Chrome/Firefox/
Device: Ipad 6th gen.
IOS: 14.8

Description:
When clicking on any room, then clicking on search room, the refresh browser icon refreshes page back to "Room" page, but won't refresh actual page user is on while using Chrome & Firefox.

Expected Behavior:
User should be able to refresh the current page they are on by clicking on the refresh button on browser.

Actual Behavior:
Currently refresh kicks user back to "room" page . Doesn't refresh current page the user is on when searching the room. 

Steps to reproduce issue:
1.Goto website 
2.Click into Game 
3.Click into any room 
4.Click search room
5.Clicked on refresh icon in browser

*** Additional Notes: 
Keyboard buttons are non-responsive for refreshing.Could be a setting on laptops however, it was tested regardless.
CG: Also removes players' keys if refreshed

**Comment by luceroweb** [comment]
@alberme is our code engineering editor. Albert, should we consider adding the event modal to the URL or as a localStorage item so that it will display when the user refreshes the room page?

cc @jennah559 @lreyes-qae

**Comment by alberme** [comment]
@luceroweb we could easily add a piece of state into localStorage and load it back in after browser refresh so that the event modal will pop up

cc @jennah559 @lreyes-qae

**Comment by alberme** [comment]
@jennah559 I have implemented persistence for those events when searching the rooms so that on browser refresh, the user will not get kicked back to the room page and have to click "Search Room" again. Please test to confirm.

cc @luceroweb  @lreyes-qae

**Comment by alberme** [comment]
@jennah559 Another note, I am aware the keys do not persist in the user's inventory after browser refresh. I did not realize that until I demoed the changes I made and reread your ticket so that additional fix unfortunately did not make it to production.

cc @luceroweb @lreyes-qae

**Comment by ghost** [comment]
Hi,

Refresh confirmed. As for the keys, we weren't sure if it could be done so,
that is why it was just a side note. Thank You

*Jennifer Hughes* (She/Her)
QA Apprentice | Bitwise Industries
 ***@***.*** | bitwiseindustries.com/
<https://bitwiseindustries.com>
700 Van Ness Avenue, Fresno, CA 93721
Stay up-to-date on everything Bitwise
<https://bitwiseindustries.com/everything-bitwise/>
