### ISSUE TITLE
Clown Puppet text suggestions

### ISSUE THREAD

**Issue by migriva** [luceroweb/haunted-house-game#116]
## ***Environment***
Device: Dell Precision 3560
Processor: 11th Gen Intel® Core™ i5-1135G7 @ 2.40GHz × 8 
Browser: Google Chrome Version 95.0.4638.54 (Official Build) (64-bit)
User type: User

## ***Description***

When encountering the Clown Puppet the user is presented with a scenario that may have grammatical errors.

## ***Expected Behavior***

The user expects that all text aspects of the game be clear and grammatically correct.

## ***Actual Behavior***

The Clown Puppet text can be construed as difficult to read due to syntax and grammar errors.

## ***Steps to Reproduce Issue***
1. Go to website
2. Navigate through game until you reach the Clown Puppet
3. Read all of the text surrounding the Clown Puppet.

## ***Screenshot***

![KillerClown_Grammar_Before](https://user-images.githubusercontent.com/93154253/139161134-ed1905e9-bb11-4816-ab67-83bd8b612484.jpg)

## ***Notes***
Following is a suggestion.  This could possibly be an improvement to the flow of the Clown Puppet text.

"A puppet sits on a shelf, its head is facing away from you.  As you enter the room the head slowly begins to spin around.  

It's a Clown Puppet!!!  The head stops turning, now it's facing you.  The clown is holding something in its hand.  You lunge at the clown puppet and it drops the object!  It's a harmless smoke bomb!!!  As green smoke fills the air you seize the opportunity to choose another way to overcome the Clown Puppet!!!"

**Comment by ProjectErostribe** [comment]
@migriva While I don't agree on the exact verbiage.  I do like your ending "As green smoke fills the air you seize the opportunity to choose another way to overcome the Clown Puppet."  so I made those changes.

**Comment by migriva** [comment]
Thank you for your input and your feedback.  This is a great game your team
created.  I approach all suggestions respectfully and openly.

**Comment by luceroweb** [comment]
@migriva is the issue resolved to your satisfaction? If so, we'd like to close this issue. Please let us know.
cc @ProjectErostribe @lreyes-qae

**Comment by migriva** [comment]
Yes, it works!
