### ISSUE TITLE
**Improvement** Win against the ghost by staring long enough

### ISSUE THREAD

**Issue by alberme** [luceroweb/haunted-house-game#62]
[timeframe: 40min, complexity: 1]
Bug/improvements - story

As a user I want to beat the ghost in a staring contest so that I can have another way to win.

* Assets
  * the ghost event
  * ResultAction component

* Expected Outcomes
  * Try again turns into a pass after x amount of clicks

**This user story should be worked on after all other bugs are fixed**

**Comment by ProjectErostribe** [comment]
@alberme Thank you for your suggestion, but due to limited time we are not able to implement this
