### ISSUE TITLE
Background sounds do not play immediately

### ISSUE THREAD

**Issue by alberme** [luceroweb/haunted-house-game#71]
[timeframe: 10min, complexity: 1]
Bug/improvements - story

As a user I want the sound to play immediately so I can feel immersed in the story

* Assets
  * background ambience sound
* Expected Outcomes
  * background sound should immediately play on start page

**Comment by darlanebrown** [comment]
@VictoriaLemons -  The audio now starts at the beginning and volume is turned up, which was probably the problem. It was corrected. Thank you for pointing it out.
