### ISSUE TITLE
Present Key Button has no function and no description

### ISSUE THREAD

**Issue by xchelseysee** [luceroweb/haunted-house-game#85]
Device name: HP Pavilion All-in-One 27-d0xxx
Processor: Intel(R) Core(TM) i7-10700T CPU @ 2.00GHz 1.99
System type: 64-bit operating system, x64-based processor
Browser: Google Chrome

Expected Behavior:
The user must go to one of the 3 options: Living Room, Kitchen, and Library to find a key and come back to the Hallway to present the key. This can be done using the "Present Key" button in the Hallway.

Actual Behavior:
On the "Hallway" page, the user is given 4 options: Living Room, Kitchen, Library, Present Key buttons to choose from. The Present Key button exists but if the user does not know what it supposes to do, the button looks like it's broken.

Note:
Initially, as a user, I clicked on the Present Key button because it was one of the 4 options presented on this page. I was confused that it didn't do anything so I am not sure if it's broken or left with no function until the key is found by going to the other 3 options to find the key.

**Comment by luceroweb** [comment]
@SmiJa made an edit previously to prevent the "Present Key" button from displaying until the user had either the Gold Key, Sliver Key, or both in their inventory. 
@xchelseysee Does this solution satisfy the problem?

cc @lreyes-qae

**Comment by xchelseysee** [comment]
@luceroweb @SmiJa, I saw the recent updates. Yes, this satisfies the issue.
