### ISSUE TITLE
Confusion among The Talking Heads

### ISSUE THREAD

**Issue by xchelseysee** [luceroweb/haunted-house-game#87]
Device name: HP Pavilion All-in-One 27-d0xxx
Processor: Intel(R) Core(TM) i7-10700T CPU @ 2.00GHz 1.99
System type: 64-bit operating system, x64-based processor
Browser: Microsoft Edge

Expected Behavior:
When the user gets to the "The Talking Heads" page, the User has the options of "A Coffin", "A Meal", or "A table". When choosing "A table", the User gets the line "You have failed and will meet your doom." This is GAMEOVER for the User.

Actual Behavior:
When the user gets to the "The Talking Heads" page, the user has the options of "A Coffin", "A Meal", and "A Table." When choosing "A Table," it resulted in a written line: "You have failed and will meet your doom!" Nothing happens. The User is assumed to understand the User can choose another option.

Notes:
This is the end? Is this "Gameover"? Because the Gameover sign doesn't pop up. Because it is not a clear Gameover, is it really doom? What does it mean "will meet your doom"? Does the User just pick another option?

**Comment by luceroweb** [comment]
@ProjectErostribe is our Haunted House story editor. Should we consider an edit to the "A Table" action response in order to make the story flow more smoothly when that action is selected?

@xchelseysee @lreyes-qae

**Comment by ProjectErostribe** [comment]
I agree with this suggestion and will change it to a "Try Again" message.

**Comment by ProjectErostribe** [comment]
The text now reads "You are incorrect.  Take a moment to check your logic and choose again!"

**Comment by luceroweb** [comment]
@xchelseysee please confirm whether you have seen the updated talking heads text and whether it satisfies your issue so we can close this ticket.

cc @ProjectErostribe @lreyes-qae

**Comment by xchelseysee** [comment]
@luceroweb @ProjectErostribe @lreyes-qae Confirmed. I see the updates.
