### ISSUE TITLE
Automatically presents gold key when you have both keys

### ISSUE THREAD

**Issue by rlynchjr** [luceroweb/haunted-house-game#88]
## Devices
Device name iPhone 13 Pro Max 
Google Chrome Version 95.0.4638.54 (Official Build) (x86_64)

## Description
If you have both keys and select the button to "present key", it will automatically present the gold key without giving you the option to present the silver key.

## Expected Behavior
When you select present key and you have both the silver and gold keys, the user should either be able to select which key they choose to present

## Actual Behavior
Clicking "present key" when you have both keys will automatically present the gold key.

## Steps to Reproduce Issue
*Be as detailed as possible when writing issues so that the developer can understand exactly how you found that issue and what they need to do to recreate it without further assistance.*
1. Open website
2. Search rooms until you receive the alien to receive the gold key
3. Continue searching rooms until you receive the silver key
4. Navigate back to hallway
5. Click Present Key

## Screenshots

N/A

## Notes
I checked to see if it mattered which order you receive the keys and it does not; the gold key is always presented first even if you have both keys.

**Comment by luceroweb** [comment]
The automatic selection of the Gold Key first was a decision in order to simplify game play so we could deploy to production more quickly. That said...
@ProjectErostribe is our Haunted House story editor, and @alberme is our code editor. Albert & Myles, how difficult would it be to allow the user to choose which key to present when they have both keys in their inventory?

@rlynchjr @lreyes-qae

**Comment by ProjectErostribe** [comment]
This was built intentionally so we voted to keep it as is.

**Comment by alberme** [comment]
@luceroweb code wise it's not difficult to implement but it all comes down to @ProjectErostribe discretion

**Comment by ProjectErostribe** [comment]
Thank you for this suggestion, but we're going to keep it as it and close this ticket.

**Comment by rlynchjr** [comment]
@ProjectErostribe Thank you for the explanation. I understand why this was the route taken.
