### ISSUE TITLE
Repetitive action if chose wrong choice ending game

### ISSUE THREAD

**Issue by Kvu24** [luceroweb/haunted-house-game#90]
## ***Environment***
Device: HP ProBook 440 G7
Processor: Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz   2.11 GHz
Version: 10.0.19042 Build 19042
Browser: Google Chrome Version 90.0.4430.212 (Official Build) (64-bit)
User type: User

## ***Description***
User is taking to same scenario after choosing wrong choice previous game and keep repeating until user choose correct answer

## ***Expected Behavior***
Users should be able to encounter different scenario if fail to select correct action when game over

## ***Actual Behavior***
Users encountered the same scenario (Zombie) after failing to to select correct action (Game over) and can repetitively reproduce it until choosing the correct action answer

## ***Steps to Reproduce Issue***
1. Go to site
2. Click "Gameplay"
3. Search Kitchen
4. Search for the Zombie that if you choose to attack "Game over"
5. Restart game and "Skip to Gameplay" 
6. Enter Kitchen and the Zombie should appear again

## ***Recording***

https://user-images.githubusercontent.com/79952827/139125587-9d1b72ea-e595-4f7c-bb0c-0eb29ef2b483.mp4

## ***Notes***
User are allow to move to next scenario once correct action are chose

**Comment by alberme** [comment]
@Kvu24 @lreyes-qae fixed the problem so now that users can encounter different events after game restart

**Comment by luceroweb** [comment]
@Kvu24 could you please re-test to confirm that this bug is fixed?

**Comment by Kvu24** [comment]
@luceroweb @alberme  @lreyes-qae  - Bug is fixed great work!
