### ISSUE TITLE
Audio levels incomparable between sound effects and ambient noise

### ISSUE THREAD

**Issue by VictoriaLemons** [luceroweb/haunted-house-game#94]
### Devices
Device name	DESKTOP-VRJKTUH
Processor	AMD Ryzen 7 3700X 8-Core Processor 3.59 GHz
System type	64-bit operating system, x64-based processor

Windows 10 Home 21H1

Google Chrome - Version 93.0.4577.63 (Official Build) (64-bit)

###Description

### Expected Behavior
Audio levels comparable between sound effects and ambient noise

### Actual Behavior
System audio must be quite high before monitor or headphones pick up the sounds

### Steps to Reproduce Issue
"1. Go to site 
2. Click forward to hallway 5/5
3. mute then unmute audio
4. observe difference in volume of door squeak on room enterance"

### Notes
better with headphones but even then to hear it comfortably the volume must be pretty high

**Comment by luceroweb** [comment]
@darlanebrown is our audio editor. Darla, should we consider increasing the background audio to make it easier to hear?

cc @VictoriaLemons @lreyes-qae

**Comment by luceroweb** [comment]
@VictoriaLemons,
@darlanebrown has increased the background audio. Can you hear the audio now?

**Comment by alberme** [comment]
@VictoriaLemons we have increased the volumes for all sounds. Please test to confirm the volumes are at appropriate levels

cc @luceroweb @lreyes-qae

**Comment by VictoriaLemons** [comment]
@alberme and @luceroweb,  yes, I am able to hear them at appropriate levels now. Awesome!
