### ISSUE TITLE
Audio does not repeat

### ISSUE THREAD

**Issue by VictoriaLemons** [luceroweb/haunted-house-game#95]
### Devices
Device name	DESKTOP-VRJKTUH
Processor	AMD Ryzen 7 3700X 8-Core Processor 3.59 GHz
System type	64-bit operating system, x64-based processor

Windows 10 Home 21H1

Google Chrome - Version 93.0.4577.63 (Official Build) (64-bit)

###Description

### Expected Behavior
When staying on a page, audio continues

### Actual Behavior
After a minute (timed it), audio stops. Does not restart after.

### Steps to Reproduce Issue
1. go to site 
2. proceed to Hallway 5/5
3. mute then unmute 
4. stay on page single for over a minute
observe audio end

### Notes
This occurs on hallway and room pages
Question to DEV: Is this expected behavior?

**Comment by luceroweb** [comment]
@VictoriaLemons We are unable to reproduce this issue. Can you demo the issue?
@lreyes-qae

**Comment by VictoriaLemons** [comment]
@luceroweb looks like its been fixed!
