### ISSUE TITLE
Game title moves to bottom of screen on "Win" screen

### ISSUE THREAD

**Issue by rlynchjr** [luceroweb/haunted-house-game#97]
## Devices
Device name - MacBook Pro (Retina, 15-inch, Early 2013)
Processor 2.7 GHz Quad-Core Intel Core i7
System type 64-bit operating system, x64-based processorGoogle Chrome Version 95.0.4638.54 (Official Build) (x86_64)

## Description
Game title appears at the bottom of the screen when you successful beat the game but appears at the top of the screen on the home screen.

## Expected Behavior
Game title should stay at the top of the screen to be consistent with rest of the game

## Actual Behavior
After you correctly present the silver key, the title of the game appears at the very bottom of the screen below all text. 

## Steps to Reproduce Issue
*Be as detailed as possible when writing issues so that the developer can understand exactly how you found that issue and what they need to do to recreate it without further assistance.*
1. Open website
2. Search rooms until you receive the silver key
3. Navigate back to hallway
4. Click Present Key

## Screenshots

<img width="1440" alt="Screen Shot 2021-10-27 at 11 32 52 AM" src="https://user-images.githubusercontent.com/93146288/139126504-98f14079-4b2d-43f7-a876-4d7bb413615b.png">
<img width="1440" alt="Screen Shot 2021-10-27 at 11 32 56 AM" src="https://user-images.githubusercontent.com/93146288/139126533-f3c972b6-c4fb-45f0-9115-33e5626c63e9.png">
<img width="1440" alt="Screen Shot 2021-10-27 at 11 33 00 AM" src="https://user-images.githubusercontent.com/93146288/139126563-f709c814-d07a-46df-bda6-0702f84ec60d.png">

## Notes
Immediately restarting a game after winning a game makes the title "bounce" from bottom to top, which may negatively impact users thoughts on the game

**Comment by luceroweb** [comment]
@ProjectErostribe and @SmiJa are the design leads for the Haunted House Game. How do you two feel about moving the Game Header to the top of the Game Won page in order to prevent the "bounce" from the bottom to the top of the page when you click "Restart Game"?
cc @rlynchjr @lreyes-qae

**Comment by ProjectErostribe** [comment]
We all decided we'll do this since originally the only purpose of it being on the bottom was so that there was a visible difference from the startGame.js page.

**Comment by SmiJa** [comment]
@rlynchjr the header has now been moved to the top of the page. 

cc @lreyes-qae @luceroweb  @ProjectErostribe

**Comment by rlynchjr** [comment]
@SmiJa I saw the revision and it looks great! I believe this issue can be closed now. 

cc @lreyes-qae @luceroweb @ProjectErostribe
